<!DOCTYPE html>
<html lang="en" data-theme="cupcake">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo htmlspecialchars($template['title'] ?? 'About', ENT_QUOTES, 'UTF-8'); ?></title>
	<!-- Tailwind + daisyUI via CDN -- no build step, just enough to not look like raw HTML.
	     Swap for a real build pipeline once this app grows past a scaffold. -->
	<script src="https://cdn.tailwindcss.com"></script>
	<link href="https://cdn.jsdelivr.net/npm/daisyui@4/dist/full.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="min-h-screen bg-base-200">
	<div class="navbar bg-base-100 shadow-sm px-4">
		<div class="flex-1">
			<a href="/" class="btn btn-ghost text-xl">QuioteMcpAssistant</a>
		</div>
		<div class="flex-none">
			<ul class="menu menu-horizontal px-1 gap-1">
				<li><a href="/">Home</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contact">Contact</a></li>
				<li><a href="/boom" class="text-error">/boom</a></li>
			</ul>
		</div>
	</div>
	<main class="max-w-3xl mx-auto px-4 py-12">
		<div class="card bg-base-100 shadow-xl">
			<div class="card-body">
				<h1 class="card-title text-3xl">About</h1>
				<p>This app was generated by <code class="bg-base-200 px-1 rounded">quiote new</code> --
					it demonstrates a Default module with a couple of actions, config split across
					PHP/YAML/XML, and a FrankenPHP-ready front controller.</p>
				<div class="card-actions justify-end">
					<a href="/" class="btn btn-primary btn-sm">Back home</a>
				</div>
			</div>
		</div>
	</main>
</body>
</html>
