<!DOCTYPE html>
<html lang="en" data-theme="cupcake">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo htmlspecialchars($template['title'] ?? 'Home', ENT_QUOTES, 'UTF-8'); ?></title>
	<!-- Tailwind + daisyUI via CDN -- no build step, just enough to not look like raw HTML.
	     Swap for a real build pipeline once this app grows past a scaffold. -->
	<script src="https://cdn.tailwindcss.com"></script>
	<link href="https://cdn.jsdelivr.net/npm/daisyui@4/dist/full.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="min-h-screen bg-base-200">
	<div class="navbar bg-base-100 shadow-sm px-4">
		<div class="flex-1">
			<a href="/" class="btn btn-ghost text-xl">QuioteMcpAssistant</a>
		</div>
		<div class="flex-none">
			<ul class="menu menu-horizontal px-1 gap-1">
				<li><a href="/">Home</a></li>
				<li><a href="/about">About</a></li>
				<li><a href="/contact">Contact</a></li>
				<li><a href="/boom" class="text-error">/boom</a></li>
			</ul>
		</div>
	</div>
	<main class="max-w-3xl mx-auto px-4 py-12">
		<div class="hero bg-base-100 rounded-box shadow-xl">
			<div class="hero-content text-center py-16">
				<div class="max-w-md">
					<h1 class="text-5xl font-bold">It works! 🎉</h1>
					<p class="py-6">This is a freshly scaffolded Quiote application, generated by
						<code class="bg-base-200 px-1 rounded">quiote new</code>.</p>
					<div class="flex justify-center gap-3">
						<a href="/about" class="btn btn-primary">About this app</a>
						<a href="/boom" class="btn btn-error btn-outline">Trigger an error</a>
					</div>
				</div>
			</div>
		</div>
		<div role="alert" class="alert alert-info mt-8">
			<span>Try <code>/boom</code> with <code>core.developer_exceptions</code> on and off in
				<code>Config/settings.*</code> to see the difference between the Whoops developer
				page and the safe generic response.</span>
		</div>
	</main>
</body>
</html>
