<?php
declare(strict_types=1);

namespace QuioteMcpAssistant\Mcp\Conventions;

/**
 * Hand-authored "convention cards": short, task-oriented notes the prose docs
 * don't always state crisply -- the class-per-action verb
 * model, config file formats, the DI attributes/API, the PluginRegistrar
 * surface, validator declaration, database driver aliases, and the MCP seam.
 *
 * These are the one hand-maintained knowledge source (docs are generated by
 * `mcp:docs:sync`); each card cross-references the authoritative doc URI so a
 * caller can `resources/read` the full page.
 */
final class ConventionCards
{
    /** @return list<string> */
    public static function topics(): array
    {
        return array_keys(self::cards());
    }

    /** @return array{title: string, body: string}|null */
    public static function get(string $topic): ?array
    {
        return self::cards()[strtolower(trim($topic))] ?? null;
    }

    /** @return array<string, array{title: string, body: string}> */
    private static function cards(): array
    {
        return [
            'actions' => [
                'title' => 'Actions & the verb model',
                'body' => <<<'MD'
                    An action is one class per action, extending `Quiote\Action\Action`, in
                    `Modules/<Module>/Actions/<Name>Action.php`. The base class defines **no**
                    `execute*` methods — the framework calls one based on the HTTP verb:

                    | Verb | Method |
                    |---|---|
                    | GET/HEAD/OPTIONS/TRACE | `executeRead` |
                    | POST | `executeWrite` |
                    | PUT/PATCH | `executeUpdate` |
                    | DELETE | `executeRemove` |

                    Resolution order: `execute<Verb>` (e.g. `executePut`) → semantic method
                    (`executeRead`/…) → bare `execute()` → `getDefaultViewName()`.

                    An `execute*` method takes a `Quiote\Request\WebRequest` and returns a **view
                    name** (string), e.g. `'Success'`. Pass data to the view with
                    `$this->setAttribute($name, $value)`. Never write output directly.

                    Useful hooks: `isSimple()` (return true to skip validation),
                    `isSecure()`/`getCredentials()` (authorization), `getDefaultViewName()`,
                    `handleError()`, `registerValidators()`.

                    See `quiote-docs://architecture/actions-and-views`.
                    MD,
            ],
            'routing' => [
                'title' => 'Routing',
                'body' => <<<'MD'
                    Two coexisting styles, merged into one `RouteCollection`:

                    1. **Routing subclass** (general): subclass `Quiote\Routing\Routing`, build a
                       `Symfony\Component\Routing\RouteCollection` in `build()`, and point the
                       `routing` factory role at it. Each route carries `_module`/`_action`
                       defaults, and a `$meta[name] = ['gen_path'=>…, 'path'=>…, 'cut'=>false]`
                       entry for reverse generation. Call `AttributeRoutes::mergeInto($routes, $meta)`
                       at the end to fold in attribute routes.
                    2. **`#[Route]` attributes** on action classes, discovered by the scanner.

                    Use modern placeholders + `requirements` for constraints — NOT inline
                    `{name:regex}` syntax (its braces break Symfony's matcher compilation).

                    See `quiote-docs://basics/routing`.
                    MD,
            ],
            'config' => [
                'title' => 'Configuration & file formats',
                'body' => <<<'MD'
                    One app mixes three config formats, one per file:

                    - **`Config/settings.php`** — a PHP array of `core.*` settings and the
                      `plugins` list. Keys: `core.app_name`, `core.namespace_prefix`,
                      `core.debug`, `core.use_database`, `core.use_logging`, `core.use_security`,
                      `core.default_context`, etc. (settings may also be `.yaml`/`.xml`).
                    - **`Config/factories.yaml`** — YAML mapping factory roles (`controller`,
                      `routing`, `request`, `response`, `user`, …) to `{class, params}`.
                    - **`Config/databases.xml`** and **`Config/output_types.xml`** — XML.

                    Read settings at runtime with `Quiote\Config\Config::get('key', $default)`;
                    `Config::has()` / `Config::set($k, $v, $overwrite)`.

                    See `quiote-docs://architecture/configuration` and
                    `quiote-docs://architecture/settings-reference`.
                    MD,
            ],
            'di' => [
                'title' => 'DI container',
                'body' => <<<'MD'
                    `Quiote\DI\Container` is a PSR-11 container with three scopes:
                    `SCOPE_SINGLETON` (once per worker), `SCOPE_TRANSIENT` (fresh each time),
                    `SCOPE_REQUEST` (once per request, cleared on `reset()`). Prefer transient/
                    request; use singleton only for verified-stateless services (workers are
                    long-lived).

                    Register with `set($id, $concrete, $scope, $params)`, `setFactory($id, $fn)`,
                    `alias($interface, $id)` — there is no `bind()`/`register()`.

                    Resolve with `get()` (memoized per scope, detects cycles), `make()` (always
                    fresh — used for actions/views), `has()` (explicit registrations only).
                    Autowiring resolves constructor params by registered value, then by type.

                    See `quiote-docs://architecture/container`.
                    MD,
            ],
            'plugins' => [
                'title' => 'Plugins & PluginRegistrar',
                'body' => <<<'MD'
                    A plugin implements `Quiote\Plugin\PluginInterface`: `name()` + a
                    `register(PluginRegistrar $r)` called **once at boot**. It adds no new
                    mechanism — each `PluginRegistrar` method (fluent) routes to an existing seam:

                    - `configDefault($key, $value)` — set-if-absent config default
                    - `service($id, $concrete, $scope, ...$aliases)` — DI service
                    - `middleware($fqcn, $factory, $after, $before, $priority)` / `attributedMiddleware($fqcn)`
                    - `listen($eventClass, $listener, $priority)` — event listener
                    - `moduleDirectory($dir)` — a `#[Route]` scan root
                    - `command($fqcn)` — a console command
                    - `httpClient($name, $configurator)` — a named HTTP client
                    - `databaseDriver($alias, $adapterClass)` — a DB adapter alias
                    - `mcpTool(...)` / `mcpResource(...)` / `mcpPrompt(...)` — MCP capabilities

                    Enable a plugin by listing its class-string in the `plugins` config key.

                    See `quiote-docs://architecture/plugins`.
                    MD,
            ],
            'database' => [
                'title' => 'Database connections',
                'body' => <<<'MD'
                    Declare connections in `Config/databases.xml`, naming an adapter by driver
                    alias; Quiote instantiates and lifecycle-manages it. Set
                    `core.use_database = true` in settings.

                    Each connection is a `Quiote\Database\Database` **lifecycle wrapper**, not the
                    raw connection. Get it via the context / DI:

                    ```php
                    $db   = $context->getDatabaseManager()->getDatabase('main');
                    $conn = $db->getConnection(); // PDO, or the ORM object for that adapter
                    ```

                    Built-in raw driver: PDO. First-class ORM adapters (opt-in plugins): Eloquent,
                    Doctrine ORM, Doctrine DBAL, Cycle ORM, Propulsion. Driver aliases must be valid
                    PHP labels (e.g. `doctrine_dbal`, not `doctrine-dbal`), registered via
                    `PluginRegistrar::databaseDriver()`.

                    See `quiote-docs://basics/databases`.
                    MD,
            ],
            'validation' => [
                'title' => 'Input validation',
                'body' => <<<'MD'
                    Quiote validates input **before** the action runs and enforces a strict rule:
                    an action can only read parameters a validator approved — unvalidated input is
                    inaccessible.

                    Declare validators with the fluent `Quiote\Validator\Compiler\Runtime\ValidatorBuilder`,
                    either by overriding `registerValidators()` (or the per-verb
                    `registerWriteValidators()` / `registerUpdateValidators()` / … hooks) on the
                    action, or in a `Modules/<Module>/Validate/` file returning a closure:

                    ```php
                    return static function (ValidatorBuilder $v): void {
                        $v->string('name', required: true)->minLength(2)->maxLength(100);
                        $v->email('email', required: true);
                        $v->enum('status', ['draft', 'published'], required: true);
                    };
                    ```

                    Validators: `string`, `number`, `boolean`, `email`, `enum`, `regex`, `json`,
                    `isNotEmpty`, `isSet`, `group`, `raw`. Chain `->error()`, `->trim()`,
                    `->export()`, etc. To skip validation entirely, return true from `isSimple()`.

                    See `quiote-docs://basics/validation` and `quiote-docs://advanced/advanced-validation`.
                    MD,
            ],
            'mcp' => [
                'title' => 'Exposing an app over MCP',
                'body' => <<<'MD'
                    The framework exposes a Quiote app as an MCP server via `Quiote\Mcp\McpPlugin`
                    (add it to `plugins`) + `mcp.enabled = true`. Transports: stdio (`mcp:serve`)
                    and Streamable HTTP.

                    Register capabilities **manually** in a plugin's `register()` — there is no
                    attribute discovery for plain handler classes:

                    - `$r->mcpTool($fqcn, $method, $name, $description, $inputSchema, $outputSchema)`
                    - `$r->mcpResource($fqcn, $uri, $method, $name, $description, $mimeType)`
                    - `$r->mcpPrompt($fqcn, $method, $name, $description)`

                    Handlers are resolved through the DI container; the handler method's params map
                    from the call arguments by name (resource handlers also receive `uri`). A tool
                    handler returns a string/array; a resource handler a string; a prompt handler an
                    array of `['role'=>…, 'content'=>…]` messages.

                    Separately, an existing `#[Route]` action can be exposed as a tool by adding
                    `#[McpTool]` and setting `mcp.expose_actions = true`. Its `inputSchema` is
                    derived automatically from the action's own validators (scoped to the verb the
                    route dispatches to) — one validator declaration drives both HTTP validation
                    and the tool's advertised schema.

                    See `quiote-docs://architecture/plugins`. This very app is the reference example.
                    MD,
            ],
        ];
    }
}
