<?php
declare(strict_types=1);

namespace QuioteMcpAssistant\Mcp\Conventions;

/**
 * Hand-authored "convention cards": short, task-oriented notes the prose docs
 * don't always state crisply -- the class-per-action verb
 * model, config file formats, the DI attributes/API, the PluginRegistrar
 * surface, validator declaration, database driver aliases, and the MCP seam.
 *
 * These are the one hand-maintained knowledge source (docs are generated by
 * `mcp:docs:sync`); each card cross-references the authoritative doc URI so a
 * caller can `resources/read` the full page.
 */
final class ConventionCards
{
    /** @return list<string> */
    public static function topics(): array
    {
        return array_keys(self::cards());
    }

    /** @return array{title: string, body: string}|null */
    public static function get(string $topic): ?array
    {
        return self::cards()[strtolower(trim($topic))] ?? null;
    }

    /** @return array<string, array{title: string, body: string}> */
    private static function cards(): array
    {
        return [
            'actions' => [
                'title' => 'Actions & the verb model',
                'body' => <<<'MD'
                    An action is one class per action, extending `Quiote\Action\Action`, in
                    `Modules/<Module>/Actions/<Name>Action.php`. The base class defines **no**
                    `execute*` methods — the framework calls one based on the HTTP verb:

                    | Verb | Method |
                    |---|---|
                    | GET/HEAD/OPTIONS/TRACE | `executeRead` |
                    | POST | `executeWrite` |
                    | PUT/PATCH | `executeUpdate` |
                    | DELETE | `executeRemove` |

                    Resolution order: `execute<Verb>` (e.g. `executePut`) → semantic method
                    (`executeRead`/…) → bare `execute()` → `getDefaultViewName()`.

                    An `execute*` method takes a `Quiote\Request\WebRequest` and returns a **view
                    name** (string), e.g. `'Success'`. Pass data to the view with
                    `$this->setAttribute($name, $value)`. Never write output directly.

                    Useful hooks: `isSimple()` (return true to skip validation),
                    `isSecure()`/`getCredentials()` (authorization), `getDefaultViewName()`,
                    `handleError()`, `registerValidators()`.

                    See `quiote-docs://architecture/actions-and-views`.
                    MD,
            ],
            'routing' => [
                'title' => 'Routing',
                'body' => <<<'MD'
                    Two coexisting styles, merged into one `RouteCollection`:

                    1. **Routing subclass** (general): subclass `Quiote\Routing\Routing`, build a
                       `Symfony\Component\Routing\RouteCollection` in `build()`, and point the
                       `routing` factory role at it. Each route carries `_module`/`_action`
                       defaults, and a `$meta[name] = ['gen_path'=>…, 'path'=>…, 'cut'=>false]`
                       entry for reverse generation. Call `AttributeRoutes::mergeInto($routes, $meta)`
                       at the end to fold in attribute routes.
                    2. **`#[Route]` attributes** on action classes, discovered by the scanner.

                    Use modern placeholders + `requirements` for constraints — NOT inline
                    `{name:regex}` syntax (its braces break Symfony's matcher compilation).

                    See `quiote-docs://basics/routing`.
                    MD,
            ],
            'config' => [
                'title' => 'Configuration & file formats',
                'body' => <<<'MD'
                    One app mixes several config formats, one per file:

                    - **`Config/settings.php`** — a PHP array of `core.*` settings (and the
                      `*.` keys packages publish, e.g. `queue.*`, `filesystem.*`). Keys:
                      `core.app_name`, `core.namespace_prefix`, `core.debug`,
                      `core.use_database`, `core.use_logging`, `core.use_security`,
                      `core.default_context`, etc. (settings may also be `.yaml`/`.xml`).
                      Plugins are **not** listed here — see `Config/plugins.php` below.
                    - **`Config/plugins.php`** — the plugin activation list; entries are
                      `{class, enabled?}`. See the `plugins` card.
                    - **`Config/factories.yaml`** — YAML mapping factory roles (`controller`,
                      `routing`, `request`, `response`, `user`, `session`, …) to
                      `{class, params}`. The `session` role selects the session backend and is
                      optional (omit it and the context answers a `NullSessionBag`).
                    - **`Config/databases.xml`** and **`Config/output_types.xml`** — XML.

                    Read settings at runtime with `Quiote\Config\Config::get('key', $default)`;
                    `Config::has()` / `Config::set($k, $v, $overwrite)`.

                    See `quiote-docs://architecture/configuration` and
                    `quiote-docs://architecture/settings-reference`.
                    MD,
            ],
            'di' => [
                'title' => 'DI container',
                'body' => <<<'MD'
                    `Quiote\DI\Container` is a PSR-11 container with three scopes:
                    `SCOPE_SINGLETON` (once per worker), `SCOPE_TRANSIENT` (fresh each time),
                    `SCOPE_REQUEST` (once per request, cleared on `reset()`). Prefer transient/
                    request; use singleton only for verified-stateless services (workers are
                    long-lived).

                    Register with `set($id, $concrete, $scope, $params)`, `setFactory($id, $fn)`,
                    `alias($interface, $id)` — there is no `bind()`/`register()`.

                    Resolve with `get()` (memoized per scope, detects cycles), `make()` (always
                    fresh — used for actions/views), `has()` (explicit registrations only).
                    Autowiring resolves constructor params by registered value, then by type.

                    See `quiote-docs://architecture/container`.
                    MD,
            ],
            'plugins' => [
                'title' => 'Plugins & PluginRegistrar',
                'body' => <<<'MD'
                    A plugin implements `Quiote\Plugin\PluginInterface`: **only**
                    `register(PluginRegistrar $r)`, called **once at boot**. There is no
                    `name()` method on the interface — carry `#[Plugin(name: '…')]` instead
                    (required for a plugin activated by class-string: one without it is
                    silently refused, logged rather than thrown). Implement `NamedPlugin` only
                    when the name genuinely can't be a compile-time constant.

                    It adds no new mechanism — each `PluginRegistrar` method (fluent) routes to
                    an existing seam:

                    - `configDefault($key, $value)` — set-if-absent config default
                    - `service($id, $concrete, $scope, ...$aliases)` — DI service
                    - `middleware($fqcn, $factory, $after, $before, $priority)` / `attributedMiddleware($fqcn)`
                    - `listen($eventClass, $listener, $priority)` — event listener
                    - `moduleDirectory($dir)` — a `#[Route]` scan root
                    - `command($fqcn)` — a console command
                    - `httpClient($name, $configurator)` — a named HTTP client
                    - `databaseDriver($alias, $adapterClass)` — a DB adapter alias
                    - `developerExceptionRenderer($factory)` — the debug error renderer

                    That is the **whole** surface. In particular there is no `mcpTool()`/
                    `mcpResource()`/`mcpPrompt()` — those wrappers were removed from core by
                    the `quioteframework/mcp` split; register MCP capabilities against
                    `Quiote\Mcp\McpCatalog` instead (see the `mcp` card).

                    Activate a plugin in **`Config/plugins.{php,yaml,yml,xml}`** — a dedicated,
                    auto-discovered file, NOT a `plugins` key inside `settings.php`. Each entry
                    is `{class, enabled?}` (enabled defaults to true), not a bare class-string:

                    ```php
                    // Config/plugins.php
                    return [
                        ['class' => \Quiote\Queue\QueuePlugin::class],
                        ['class' => \App\Plugin\HealthPlugin::class, 'enabled' => false],
                    ];
                    ```

                    A module may ship its own `%core.module_dir%/<Module>/Config/plugins.xml`,
                    contributing without touching the app-level file.

                    **Ordering is load-bearing:** service contributions are applied
                    *register-if-absent*, so whichever plugin binds an id **first** wins. To
                    override a package's default binding, declare your own plugin *before* it.

                    See `quiote-docs://architecture/plugins`.
                    MD,
            ],
            'database' => [
                'title' => 'Database connections',
                'body' => <<<'MD'
                    Declare connections in `Config/databases.xml`, naming an adapter by driver
                    alias; Quiote instantiates and lifecycle-manages it. Set
                    `core.use_database = true` in settings.

                    Each connection is a `Quiote\Database\Database` **lifecycle wrapper**, not the
                    raw connection. Get it via the context / DI:

                    ```php
                    $db   = $context->getDatabaseManager()->getDatabase('main');
                    $conn = $db->getConnection(); // PDO, or the ORM object for that adapter
                    ```

                    Built-in raw driver: PDO. First-class ORM adapters (opt-in plugins): Eloquent,
                    Doctrine ORM, Doctrine DBAL, Cycle ORM, Propulsion. Driver aliases must be valid
                    PHP labels (e.g. `doctrine_dbal`, not `doctrine-dbal`), registered via
                    `PluginRegistrar::databaseDriver()`.

                    See `quiote-docs://basics/databases`.
                    MD,
            ],
            'validation' => [
                'title' => 'Input validation',
                'body' => <<<'MD'
                    Quiote validates input **before** the action runs and enforces a strict rule:
                    an action can only read parameters a validator approved — unvalidated input is
                    inaccessible.

                    Declare validators with the fluent `Quiote\Validator\Compiler\Runtime\ValidatorBuilder`,
                    either by overriding `registerValidators()` (or the per-verb
                    `registerWriteValidators()` / `registerUpdateValidators()` / … hooks) on the
                    action, or in a `Modules/<Module>/Validate/` file returning a closure:

                    ```php
                    return static function (ValidatorBuilder $v): void {
                        $v->string('name', required: true)->minLength(2)->maxLength(100);
                        $v->email('email', required: true);
                        $v->enum('status', ['draft', 'published'], required: true);
                    };
                    ```

                    Validators: `string`, `number`, `boolean`, `email`, `enum`, `regex`, `json`,
                    `isNotEmpty`, `isSet`, `group`, `raw`. Chain `->error()`, `->trim()`,
                    `->export()`, etc. To skip validation entirely, return true from `isSimple()`.

                    **Third way — `#[MapRequest]` DTOs.** Mark a constructor-promoted class
                    `#[MapRequest]`, annotate properties with
                    `Quiote\Request\Attribute\Constraint\*`, and add it as a second parameter to
                    one `execute*` method. No other registration step:

                    ```php
                    #[MapRequest]
                    final readonly class ContactDto
                    {
                        public function __construct(
                            #[StringLength(min: 2, max: 20)] public string $title,
                            #[Email] public ?string $authorEmail = null,
                        ) {}
                    }

                    public function executeWrite(WebRequest $rd, ContactDto $dto): string { … }
                    ```

                    Constraints: `NotBlank`, `StringLength`, `Range`, `Email`, `Choice`,
                    `Regexp`, `BooleanType`, `JsonType`, `DateTimeType` (all take `message:`).
                    Required-ness is read from the **constructor signature** — non-nullable with
                    no default is required. Properties need a single named type (no unions).
                    The DTO binds to that one method; other verbs declare their own shape.

                    All three styles compile to the same validators, so failures, MCP
                    `inputSchema` and OpenAPI parameters are derived identically.

                    See `quiote-docs://basics/validation` and `quiote-docs://advanced/advanced-validation`.
                    MD,
            ],
            'mcp' => [
                'title' => 'Exposing an app over MCP',
                'body' => <<<'MD'
                    The framework exposes a Quiote app as an MCP server via `Quiote\Mcp\McpPlugin`
                    (activate it in `Config/plugins.php`) + `mcp.enabled = true`. Transports:
                    stdio (`mcp:serve`) and Streamable HTTP.

                    Register capabilities **manually** in a plugin's `register()` — there is no
                    attribute discovery for plain handler classes. Register against the static
                    `Quiote\Mcp\McpCatalog`, **not** `$registrar`:

                    ```php
                    use Quiote\Mcp\McpCatalog;

                    McpCatalog::addTool([GreetTool::class, 'greet'], name: 'greet', description: '…', inputSchema: [...]);
                    McpCatalog::addResource([DocsResource::class, 'read'], 'docs://x', name: '…', mimeType: 'text/markdown');
                    McpCatalog::addPrompt([Prompts::class, 'review'], name: 'review', description: '…');
                    ```

                    - `addTool($handler, ?$name, ?$title, ?$description, ?$inputSchema, ?$outputSchema)`
                    - `addResource($handler, $uri, ?$name, ?$title, ?$description, ?$mimeType)`
                    - `addPrompt($handler, ?$name, ?$title, ?$description)`

                    `$handler` is **one** `[class-string, method]` pair (or a `\Closure`, or a
                    class-string with `__invoke`) — not separate `$fqcn`/`$method` arguments. Note
                    `$title` sits between `$name` and `$description`, so pass the rest as named
                    arguments.

                    :warning: `PluginRegistrar` has **no** `mcpTool()`/`mcpResource()`/
                    `mcpPrompt()`. Those wrappers existed on core's registrar and forwarded here,
                    but the `quioteframework/mcp` monorepo split removed them (core can't depend
                    on the now-optional MCP package) without replacements — calling them is a
                    fatal error.

                    Handlers are resolved through the DI container; the handler method's params map
                    from the call arguments by name (resource handlers also receive `uri`). A tool
                    handler returns a string/array; a resource handler a string; a prompt handler an
                    array of `['role'=>…, 'content'=>…]` messages.

                    Separately, an existing `#[Route]` action can be exposed as a tool by adding
                    `#[McpTool]` and setting `mcp.expose_actions = true`. Its `inputSchema` is
                    derived automatically from the action's own validators (scoped to the verb the
                    route dispatches to) — one validator declaration drives both HTTP validation
                    and the tool's advertised schema.

                    See `quiote-docs://architecture/plugins`. This very app is the reference example.
                    MD,
            ],
            'sessions' => [
                'title' => 'Sessions (PSR-7 native, 3.0+)',
                'body' => <<<'MD'
                    **3.0 replaced the session subsystem.** There is no `session_start()`, no
                    `$_SESSION`, and no save handler. The id rides a cookie on the PSR-7
                    request, data lives in a backend named in config, and `Set-Cookie` rides the
                    PSR-7 response — which is what makes sessions correct under worker runtimes.

                    **Pick a backend** with the `session` factory slot in
                    `Config/factories.{yaml,xml,php}`:

                    ```yaml
                    session:
                      class: Quiote\Session\FileSessionFactory
                      params:
                        dir: '%core.app_dir%/cache/sessions'
                    ```

                    Backends: `Quiote\Session\FileSessionFactory` and `PdoSessionFactory` (core),
                    plus `Redis\RedisSessionFactory` (`session-redis`),
                    `Quiote\Storage\S3\S3SessionFactory` (`session-s3`),
                    `Gcs\GcsSessionFactory` (`session-gcs`), `Azure\AzureBlobSessionFactory` /
                    `AzureTableSessionFactory` (`session-azure`). Cookie settings live on the
                    same slot: `cookie_name`, `session_cookie_lifetime`, `session_cookie_secure`,
                    `session_cookie_httponly`, `session_cookie_samesite`,
                    `session_migration_grace_seconds`.

                    **The slot is optional.** Omit it and the context answers a `NullSessionBag`
                    (reads return the default, writes discarded, `exists()` false) — right for a
                    console command, queue worker or stateless API. But note: with no session
                    cookie, `CsrfValidationMiddleware` treats *every* request as CSRF-exempt
                    while injection still adds the field, so it only looks protected.

                    **Read/write through the bag**, `$context->getSessionBag()`:

                    ```php
                    $bag = $this->getContext()->getSessionBag();
                    $bag->get($k, $default);  $bag->set($k, $v);   $bag->has($k);
                    $bag->remove($k);         $bag->exists();      $bag->getId();
                    $bag->regenerate(true);   $bag->destroy();
                    ```

                    `get()` normalizes "missing" to `$default`. `exists()` answers "does a
                    session already exist?" — consult it before persisting default/empty state
                    so an anonymous request doesn't acquire a session it never asked for; a
                    deliberate write (login, preference) should not consult it.

                    Anonymous requests no longer create a session or emit a cookie.
                    `setAuthenticated(false)` now discards contents and rotates the id.

                    See `quiote-docs://basics/sessions` and, for migrating a 2.x app,
                    `quiote-docs://getting-started/upgrading-to-3`.
                    MD,
            ],
            'queues' => [
                'title' => 'Background jobs & queues',
                'body' => <<<'MD'
                    `quioteframework/queue` adds a job abstraction; `queue-db` / `queue-redis`
                    add the persistent backends. A job implements `Quiote\Queue\Job` — one
                    `handle(): void`. It is instantiated fresh per attempt via
                    `Container::make()`, so constructor-injected services autowire and only the
                    job's own arguments travel through the queue.

                    ```php
                    $queue = $container->get(\Quiote\Queue\QueueManager::class);
                    $queue->push(SendWelcomeEmail::class, ['userId' => 5]);
                    $queue->push(SendWelcomeEmail::class, ['userId' => 5], delaySeconds: 300);
                    ```

                    Implement `RetryableJob` (extends `Job`) to override retry per job with
                    `maxAttempts(): int` and `backoffSeconds(int $attempt): int`; otherwise the
                    config defaults apply (`queue.retry.max_attempts` 3,
                    `queue.retry.backoff_seconds` 5).

                    **Drivers.** `queue.default_driver` defaults to `sync`, which runs the job
                    **inline in the pushing request** with blocking retries — fine for dev/test,
                    wrong for production. `db` (queue-db) and `redis` (queue-redis) give a real
                    backlog drained by `queue:work --driver=db` (`--max-jobs`, `--sleep`,
                    `--stop-when-empty`). `$params` must be JSON-serializable for a persistent
                    driver. Neither `db` table is created automatically — run the DDL from
                    `DbQueueDriver::schema()` / `DbFailedJobStore::schema()`.

                    **Dead letters.** Exhausted retries go to `FailedJobStoreInterface`,
                    defaulting to `LogFailedJobStore` (logs and drops — nothing to query).
                    `queue-db`'s `DbFailedJobStore` is registered but **not** bound as the
                    default; bind it yourself to get a queryable store and the
                    `queue:failed:list|retry|forget` commands.

                    See `quiote-docs://advanced/queues`.
                    MD,
            ],
            'scheduling' => [
                'title' => 'Scheduled tasks (cron)',
                'body' => <<<'MD'
                    `quioteframework/scheduler` declares *what* runs and *when* in one class;
                    the OS crontab runs `schedule:run` once a minute. Adding or moving a task is
                    a code change, not a crontab change. It layers on `quioteframework/queue`.

                    ```php
                    final class AppSchedule extends Schedule
                    {
                        protected function define(): void
                        {
                            $this->job(SendDigestEmails::class)->dailyAt('06:00');
                            $this->job(RebuildSearchIndex::class, ['full' => false])->cron('*/15 * * * *');
                            $this->call(fn(Container $c) => $c->get(Reaper::class)->gc())
                                 ->hourly()->withoutOverlapping();
                        }
                    }
                    ```

                    `->job()` **dispatches** onto `QueueManager` (the default, and the one that
                    gets retries/dead-lettering); `->call()` runs a closure in-process and
                    receives the DI `Container`. Cron specs: `->cron('*/5 * * * *')`,
                    `everyMinute()`, `hourly()`, `daily()`, `dailyAt('06:30')`. **No cron call
                    at all defaults to every minute.**

                    `withoutOverlapping(ttlSeconds: 3600)` skips (does not queue) a due
                    invocation while the lock is held. It is built on the PSR-16 cache, which
                    has no atomic add-if-absent — best-effort, **not** a distributed lock.

                    **Registering:** `SchedulerPlugin` registers a no-op default `Schedule`.
                    Because service contributions are register-if-absent, bind your subclass
                    from a small app plugin declared **before** `SchedulerPlugin` in
                    `Config/plugins.php`, or the no-op wins.

                    Crontab, one line per app:
                    `* * * * * php /path/to/app/bin/quiote schedule:run --app-dir=/path/to/app`.
                    `schedule:run` is not a daemon — it evaluates, runs the due tasks, exits
                    (non-zero if any threw; one failure doesn't block the rest).

                    See `quiote-docs://advanced/scheduling`.
                    MD,
            ],
            'filesystem' => [
                'title' => 'File storage',
                'body' => <<<'MD'
                    `Quiote\Filesystem` is a read/write/list abstraction over a named **disk**,
                    so a local directory in dev and an object store in production differ only by
                    config. It is deliberately separate from sessions and the cache — this is for
                    files the app owns (reports, uploads, exports).

                    It lives in core but is a **plugin**: activate
                    `Quiote\Filesystem\FilesystemPlugin` in `Config/plugins.php` or
                    `FilesystemManager` won't exist.

                    ```php
                    $fs = $this->getContext()->getContainer()->get(FilesystemManager::class);
                    $fs->write('reports/q3.csv', $csv);
                    $csv = $fs->read('reports/q3.csv');
                    $fs->exists('reports/q3.csv');
                    $fs->delete('reports/q3.csv');

                    $fs->disk()->size('reports/q3.csv');          // default disk
                    $fs->disk('s3')->write('exports/big.zip', $b); // a named disk
                    ```

                    `FilesystemAdapterInterface`: `read`, `write`, `delete`, `exists`, `size`,
                    `lastModified`, `listContents` (relative paths, **non-recursive**). Errors
                    are `FilesystemStorageException`, with `FileNotFoundStorageException` for
                    the missing-file case.

                    The core `local` disk resolves every path against a root
                    (`filesystem.disks.local.root`, default `storage/app`), rejects `..` and
                    absolute paths, and writes atomically via temp-file rename. Cloud disks:
                    `s3`, `gcs`, `azure` (one package + plugin each, each needing a PSR-18
                    client bound).

                    **`listContents()` throws unconditionally on all three cloud disks** — the
                    clients have no list operation. Keep your own listing in the database.

                    Out of scope by design: visibility/ACLs, MIME detection, streaming, copy/move,
                    checksums.

                    See `quiote-docs://basics/filesystem`.
                    MD,
            ],
            'sse' => [
                'title' => 'Server-Sent Events (streaming)',
                'body' => <<<'MD'
                    Everything else in the response pipeline is string-buffered.
                    `Quiote\Http\Sse\SseStreamingAction` is the one deliberate exception.
                    Implement it on an ordinary action and yield from `streamEvents()`:

                    ```php
                    class TickerAction extends Action implements SseStreamingAction
                    {
                        public function isSimple(): bool { return true; }

                        public function streamEvents(WebRequest $request): iterable
                        {
                            for ($i = 0; $i < 10; $i++) {
                                yield SseEvent::of(['tick' => $i], event: 'tick');
                                sleep(1);
                            }
                        }
                    }
                    ```

                    Return any `iterable` of `SseEvent` or plain `string` (a string is wrapped as
                    a data-only event) — a **generator** is what makes events arrive one at a
                    time rather than all at the end.

                    `SseEvent::of(string|array $data, ?string $event, ?string $id, ?int $retryMs)`
                    JSON-encodes an array argument. The response sets `Content-Type:
                    text/event-stream`, `Cache-Control: no-cache`, `Connection: keep-alive`, and
                    `X-Accel-Buffering: no` (without which nginx/Caddy buffer the whole stream).

                    This is a **parallel dispatch path**, not an output type:
                    `DispatchMiddleware` detects the interface and short-circuits, so a streaming
                    action bypasses the View layer entirely (no View, no Template, no output
                    type), caching, and validation-decision bridging — read the request object
                    directly if the stream is parameterised.

                    See `quiote-docs://advanced/server-sent-events`.
                    MD,
            ],
            'openapi' => [
                'title' => 'Generating an OpenAPI spec',
                'body' => <<<'MD'
                    `quiote openapi:generate` writes an **OpenAPI 3.1** document that is
                    *derived*, not maintained — there is no second description to drift.

                    | Part | Derived from |
                    |---|---|
                    | Paths and verbs | the route table |
                    | Parameters / request bodies | each action's **validators** |
                    | Success media type | the route's output type |
                    | Error responses | `Quiote\Http\ProblemDetails` |
                    | Summary/description | the action class's docblock |

                    ```bash
                    vendor/bin/quiote openapi:generate -o openapi.json
                    quiote openapi:generate --format=yaml --module=Orders --exclude='internal.*'
                    ```

                    Parameter placement follows what the pipeline actually reads: path
                    placeholders become path parameters; on `GET`/`HEAD`/`DELETE`/`OPTIONS`/
                    `TRACE` the rest become **query** parameters; otherwise a `requestBody`
                    offered as both `application/json` and `application/x-www-form-urlencoded`.

                    Four honest limits: **response bodies aren't described** (an action returns a
                    view name — only the media type is stated); an action with **no validators**
                    yields an operation with no parameters (absence of knowledge, not a claim);
                    **optional path placeholders become required** path parameters with a default
                    (OpenAPI has no optional-path concept); and **action docblocks are published**
                    as operation prose — disable with `core.openapi.use_action_docblocks: false`
                    or `--no-docblocks` if yours are internal notes.

                    This is the same `ActionInputSchemaResolver` derivation that gives an MCP tool
                    its `inputSchema`, `#[MapRequest]` DTOs included.

                    See `quiote-docs://advanced/openapi`.
                    MD,
            ],
            'cli' => [
                'title' => 'The quiote command-line tool',
                'body' => <<<'MD'
                    `vendor/bin/quiote`, built on Symfony Console. All app-bootstrapping commands
                    take `--app-dir` and `--env`.

                    - `new <dir>` — scaffold a whole application (`--force`, `--namespace`,
                      `--config-format=php|yaml|xml`)
                    - `serve` — local dev server
                    - `make:module`, `make:action`, `make:middleware`, `make:job` — scaffold
                      **inside** an existing app; all take `--force`/`-f` and validate names as
                      PHP class-name segments before writing
                    - `routes:list`, `about` — inspect
                    - `routes:compile`, `cache:warmup` — compile caches ahead of time
                    - `openapi:generate` — derive an API spec
                    - `queue:work`, `queue:failed:list|retry|forget` (with `quioteframework/queue`)
                    - `schedule:run` (with `quioteframework/scheduler`)
                    - `mcp:serve` (with `Quiote\Mcp\McpPlugin`)

                    ```bash
                    vendor/bin/quiote make:module Blog --with-index
                    vendor/bin/quiote make:action Post --module=Blog --methods=GET,POST --output-types=html,json
                    vendor/bin/quiote make:middleware RequestId --phase=before_action --priority=10
                    vendor/bin/quiote make:job SendWelcomeEmail --retryable
                    ```

                    Plugins contribute further commands via `PluginRegistrar::command()`.

                    Note: this MCP server's own `scaffold_*` tools cover module/action/plugin/
                    db-connection generation without shelling out.

                    See `quiote-docs://getting-started/cli`.
                    MD,
            ],
        ];
    }
}
