<?php
declare(strict_types=1);

namespace QuioteMcpAssistant\Mcp;

use Quiote\Config\Config;
use Quiote\Mcp\McpCatalog;
use Quiote\Plugin\PluginInterface;
use Quiote\Plugin\PluginRegistrar;
use QuioteMcpAssistant\Mcp\Console\DocsSyncCommand;
use QuioteMcpAssistant\Mcp\Conventions\ConventionCards;
use QuioteMcpAssistant\Mcp\Prompts\ScaffoldPrompts;
use QuioteMcpAssistant\Mcp\Recipes\RecipeBook;
use QuioteMcpAssistant\Mcp\Resources\DocsResource;
use QuioteMcpAssistant\Mcp\Tools\DescribeActionTool;
use QuioteMcpAssistant\Mcp\Tools\DescribeSymbolTool;
use QuioteMcpAssistant\Mcp\Tools\GetConventionTool;
use QuioteMcpAssistant\Mcp\Tools\GetRecipeTool;
use QuioteMcpAssistant\Mcp\Tools\ListApiTool;
use QuioteMcpAssistant\Mcp\Tools\ListDbConnectionsTool;
use QuioteMcpAssistant\Mcp\Tools\ListModulesTool;
use QuioteMcpAssistant\Mcp\Tools\ListPluginsTool;
use QuioteMcpAssistant\Mcp\Tools\ListRoutesTool;
use QuioteMcpAssistant\Mcp\Tools\ProjectInfoTool;
use QuioteMcpAssistant\Mcp\Tools\ReadConfigTool;
use QuioteMcpAssistant\Mcp\Tools\RunConsoleTool;
use QuioteMcpAssistant\Mcp\Tools\ScaffoldActionTool;
use QuioteMcpAssistant\Mcp\Tools\ScaffoldDbConnectionTool;
use QuioteMcpAssistant\Mcp\Tools\ScaffoldModuleTool;
use QuioteMcpAssistant\Mcp\Tools\ScaffoldPluginTool;
use QuioteMcpAssistant\Mcp\Tools\SearchDocsTool;
use QuioteMcpAssistant\Mcp\Introspection\ConsoleCommandWhitelist;

/**
 * The Quiote Assistant MCP server -- knowledge tools/resources/prompts plus,
 * when a target app is configured, project-aware introspection and
 * scaffolding tools.
 *
 * Because the framework has *no* attribute discovery for plain
 * `#[McpResource]`/`#[McpPrompt]`/`#[McpTool]` classes (only `#[Route]` actions
 * carrying `#[McpTool]` are scanned), every capability this app
 * exposes is registered *manually* here, directly against {@see McpCatalog}.
 *
 * Historical note: `PluginRegistrar::mcpTool()`/`mcpResource()`/`mcpPrompt()`
 * convenience wrappers used to exist on core's `PluginRegistrar` and forwarded
 * to `McpCatalog`; the framework's `quioteframework/mcp` monorepo split
 * removed them from core (core can no longer depend on the now-optional MCP
 * package) without replacing them with anything on the mcp package's side.
 * `$this->mcpTool()`/`mcpResource()`/`mcpPrompt()` below reproduce that exact
 * former behavior locally -- one `[handlerFqcn, method]` pair translation,
 * kept in one place -- so every call site below is otherwise unchanged.
 *
 * Add this class (and `Quiote\Mcp\McpPlugin`, from the separate
 * `quioteframework/mcp` package) to the `plugins` config key and set
 * `mcp.enabled = true` to serve it over stdio via `mcp:serve` /
 * `bin/quiote-assistant`.
 */
final class AssistantPlugin implements PluginInterface
{
    public function name(): string
    {
        return 'quiote/assistant';
    }

    public function register(PluginRegistrar $registrar): void
    {
        // Sensible knowledge-server identity (app settings.php still wins).
        $registrar->configDefault('mcp.server_name', 'quiote-assistant');
        $registrar->configDefault('mcp.server_version', '0.1.0');

        // The re-runnable docs bundler.
        $registrar->command(DocsSyncCommand::class);

        $this->registerDocResources();
        $this->registerTools();
        $this->registerPrompts();
        $this->registerProjectTools();
    }

    /**
     * One MCP resource per bundled doc, all served by the single
     * {@see DocsResource::read()} handler (the SDK passes the requested `uri`
     * to the handler, so one method serves every doc). The manifest is
     * generated by `mcp:docs:sync`; if it hasn't been run yet we simply expose
     * no doc resources rather than failing to boot.
     */
    private function registerDocResources(): void
    {
        $manifestFile = __DIR__ . '/Resources/manifest.php';
        if (!is_file($manifestFile)) {
            return;
        }

        /** @var array<string, array{file: string, path: string, title: string, description: string}> $manifest */
        $manifest = require $manifestFile;

        foreach ($manifest as $uri => $meta) {
            // MCP resource names allow only [A-Za-z0-9_-] -- the doc's slash-
            // separated path (e.g. basics/routing) must be flattened.
            $name = preg_replace('/[^A-Za-z0-9_-]+/', '_', $meta['path']) ?? $meta['path'];

            $this->mcpResource(
                handlerFqcn: DocsResource::class,
                uri: $uri,
                method: 'read',
                name: $name,
                description: $meta['title'] . ($meta['description'] !== '' ? ' — ' . $meta['description'] : ''),
                mimeType: 'text/markdown',
            );
        }
    }

    private function registerTools(): void
    {
        $this->mcpTool(
            handlerFqcn: SearchDocsTool::class,
            method: 'search',
            name: 'search_docs',
            description: 'Full-text search across the Quiote documentation. Returns ranked '
                . 'excerpts with their resource URI (readable via resources/read) so answers '
                . 'can cite authoritative docs.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'query' => [
                        'type' => 'string',
                        'description' => 'Search terms, e.g. "define a route" or "database connection".',
                    ],
                    'limit' => [
                        'type' => 'integer',
                        'description' => 'Maximum number of results to return (default 5).',
                        'minimum' => 1,
                        'maximum' => 20,
                    ],
                ],
                'required' => ['query'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: GetConventionTool::class,
            method: 'get',
            name: 'get_convention',
            description: 'Return a concise, task-oriented Quiote convention card for a topic '
                . '(' . implode(', ', ConventionCards::topics()) . ').',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'topic' => [
                        'type' => 'string',
                        'description' => 'The convention topic to fetch.',
                        'enum' => ConventionCards::topics(),
                    ],
                ],
                'required' => ['topic'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: GetRecipeTool::class,
            method: 'get',
            name: 'get_recipe',
            description: 'Return step-by-step instructions + runnable code for a concrete task '
                . '(' . implode(', ', RecipeBook::tasks()) . ').',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'task' => [
                        'type' => 'string',
                        'description' => 'The task to fetch a recipe for.',
                        'enum' => RecipeBook::tasks(),
                    ],
                ],
                'required' => ['task'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: DescribeSymbolTool::class,
            method: 'describe',
            name: 'describe_symbol',
            description: 'Reflection-based signature + docblock for a Quiote framework class, '
                . 'interface, trait, or enum (optionally "Class::method" for one method), so it '
                . 'never drifts from the actual code.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'symbol' => [
                        'type' => 'string',
                        'description' => 'A Quiote\\* FQCN, e.g. "Quiote\\Action\\Action" or "Quiote\\Action\\Action::executeRead".',
                    ],
                ],
                'required' => ['symbol'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: ListApiTool::class,
            method: 'list',
            name: 'list_api',
            description: 'Browse the Quiote\\* namespace tree. Call with no arguments to list '
                . 'top-level namespaces, then again with one of those as "namespace" to list its '
                . 'classes (pass the result to describe_symbol for full detail).',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'namespace' => [
                        'type' => 'string',
                        'description' => 'A Quiote\\* namespace prefix, e.g. "Quiote\\Mcp". Omit to list top-level namespaces.',
                    ],
                    'limit' => [
                        'type' => 'integer',
                        'description' => 'Maximum number of classes to return (default 50).',
                        'minimum' => 1,
                        'maximum' => 200,
                    ],
                ],
                'additionalProperties' => false,
            ],
        );
    }

    /**
     * The "project-aware" tools -- only registered when `bin/quiote-assistant`
     * was launched with `--target-app-dir`, so a plain knowledge-only server
     * (the common case) doesn't advertise tools that would only ever fail
     * with "no target app configured." The read-only ones (`project_info`
     * through `read_config`) never write; the ones that can (`scaffold_*`,
     * `run_console`) only ever *create new files* (never overwrite -- see
     * `ScaffoldWriter`) and default `dry_run` to `true`. Every one delegates to
     * {@see \QuioteMcpAssistant\Mcp\Introspection\TargetAppIntrospector} (or,
     * for `run_console`, `ConsoleRunner`), which runs an isolated subprocess
     * against the target app -- required because `Quiote\Config\Config`/
     * `Context`/`PluginManager` are static, process-wide singletons that lock
     * the bootstrapped app's `core.app_dir` readonly, so this
     * (already-bootstrapped) assistant cannot also bootstrap an arbitrary
     * second app in the same process.
     */
    private function registerProjectTools(): void
    {
        if (trim(Config::getNullableString('assistant.target_app_dir') ?? '') === '') {
            return;
        }

        $this->mcpTool(
            handlerFqcn: ProjectInfoTool::class,
            method: 'info',
            name: 'project_info',
            description: 'Overview of the target Quiote app -- environment, default context, '
                . 'enabled plugins, and module list -- read live from the bootstrapped app. Call '
                . 'this instead of reading Config/*.php/xml by hand: it reflects what actually '
                . 'loaded, not just what a config file declares.',
            // An empty PHP array for "properties" serializes as a JSON array
            // ([]), which the SDK's opis/json-schema validator rejects
            // ("properties must be an object") -- force object serialization.
            inputSchema: ['type' => 'object', 'properties' => new \stdClass(), 'additionalProperties' => false],
        );

        $this->mcpTool(
            handlerFqcn: ListRoutesTool::class,
            method: 'list',
            name: 'list_routes',
            description: 'Every route the target app actually resolves with, read live from its '
                . 'RouteCollection (equivalent to running `quiote routes:list`). Call this instead '
                . 'of grepping the app for #[Route] attributes: a Routing subclass can also declare '
                . 'routes programmatically, which a source scan would miss but this tool always sees. '
                . 'If the caller only wants a specific module\'s (and/or action\'s) routes, pass '
                . '"module" (and/or "action") to filter server-side instead of fetching every route '
                . 'and filtering client-side -- a real app can have hundreds of routes.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'module' => ['type' => 'string', 'description' => 'Only routes whose "_module" default matches this (case-insensitive), e.g. "Library".'],
                    'action' => ['type' => 'string', 'description' => 'Only routes whose "_action" default matches this (case-insensitive), e.g. "Index".'],
                ],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: DescribeActionTool::class,
            method: 'describe',
            name: 'describe_action',
            description: 'Verbs, validator-derived input schema per verb, required credentials, '
                . 'and default view name for one action.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'action' => [
                        'type' => 'string',
                        'description' => '"Module.Action", e.g. "Blog.Post".',
                    ],
                ],
                'required' => ['action'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: ListDbConnectionsTool::class,
            method: 'list',
            name: 'list_db_connections',
            description: 'Configured database connections: adapter class and parameter names '
                . 'only, never parameter values (DSNs/credentials are never disclosed). Call this '
                . 'instead of reading Config/databases.xml directly, which would expose the '
                . 'credentials this tool deliberately redacts.',
            // An empty PHP array for "properties" serializes as a JSON array
            // ([]), which the SDK's opis/json-schema validator rejects
            // ("properties must be an object") -- force object serialization.
            inputSchema: ['type' => 'object', 'properties' => new \stdClass(), 'additionalProperties' => false],
        );

        $this->mcpTool(
            handlerFqcn: ListPluginsTool::class,
            method: 'list',
            name: 'list_plugins',
            description: 'Plugins actually registered during the target app\'s bootstrap. Call '
                . 'this instead of reading the "plugins" key in Config/settings.* by hand -- a '
                . 'plugin can also be registered programmatically via PluginManager::add() before '
                . 'bootstrap (e.g. in a front controller), which a config-file read alone would miss.',
            // An empty PHP array for "properties" serializes as a JSON array
            // ([]), which the SDK's opis/json-schema validator rejects
            // ("properties must be an object") -- force object serialization.
            inputSchema: ['type' => 'object', 'properties' => new \stdClass(), 'additionalProperties' => false],
        );

        $this->mcpTool(
            handlerFqcn: ListModulesTool::class,
            method: 'list',
            name: 'list_modules',
            description: 'Module names discovered under the target app\'s module directory.',
            // An empty PHP array for "properties" serializes as a JSON array
            // ([]), which the SDK's opis/json-schema validator rejects
            // ("properties must be an object") -- force object serialization.
            inputSchema: ['type' => 'object', 'properties' => new \stdClass(), 'additionalProperties' => false],
        );

        $this->mcpTool(
            handlerFqcn: ReadConfigTool::class,
            method: 'read',
            name: 'read_config',
            description: 'Read one setting from the target app, restricted to an explicit '
                . 'allowlist (never secrets like mcp.auth_token or DB credentials). Omit "key" '
                . 'to see the allowlist.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'key' => ['type' => 'string', 'description' => 'A whitelisted config key, e.g. "core.use_database".'],
                ],
                'additionalProperties' => false,
            ],
        );

        // Scaffolding + run_console. All default dry_run to true
        // and never overwrite an existing file (see ScaffoldWriter).
        $this->mcpTool(
            handlerFqcn: ScaffoldModuleTool::class,
            method: 'scaffold',
            name: 'scaffold_module',
            description: 'Create a new module skeleton (Index action + view + template). '
                . 'dry_run defaults to true (returns a diff, writes nothing); pass dry_run=false '
                . 'to actually write. Never overwrites an existing file.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'module' => ['type' => 'string', 'description' => 'PascalCase module name, e.g. "Blog".'],
                    'dry_run' => ['type' => 'boolean', 'description' => 'Preview only (default true).'],
                ],
                'required' => ['module'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: ScaffoldActionTool::class,
            method: 'scaffold',
            name: 'scaffold_action',
            description: 'Create a new action + its view + template(s), with a #[Route] attribute '
                . 'for reachability. "formats" controls which output types the view serves -- each '
                . 'gets its own execute<Format>() method ("html" also gets a template; others return '
                . 'their body directly, e.g. executeJson() returning json_encode(...)). A requested '
                . 'format not yet declared in Config/output_types.xml is reported back as a '
                . 'ready-to-paste snippet (this tool never edits that file). dry_run defaults to '
                . 'true; never overwrites an existing file.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'module' => ['type' => 'string', 'description' => 'PascalCase module name, e.g. "Blog".'],
                    'action' => ['type' => 'string', 'description' => 'PascalCase action name, e.g. "Post".'],
                    'verbs' => [
                        'type' => 'array',
                        'items' => ['type' => 'string', 'enum' => ['read', 'write', 'update', 'remove']],
                        'description' => 'One or more of read/write/update/remove (default: ["read"]).',
                    ],
                    'formats' => [
                        'type' => 'array',
                        'items' => ['type' => 'string'],
                        'description' => 'One or more output type names the view should serve, e.g. '
                            . '["html", "json"] (default: ["html"]).',
                    ],
                    'dry_run' => ['type' => 'boolean', 'description' => 'Preview only (default true).'],
                ],
                'required' => ['module', 'action'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: ScaffoldPluginTool::class,
            method: 'scaffold',
            name: 'scaffold_plugin',
            description: 'Create a new plugin class (never auto-registers it in Config/settings.* '
                . '-- the response tells you the one line to add). dry_run defaults to true; '
                . 'never overwrites an existing file.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'name' => ['type' => 'string', 'description' => 'PascalCase plugin name, e.g. "Health".'],
                    'dry_run' => ['type' => 'boolean', 'description' => 'Preview only (default true).'],
                ],
                'required' => ['name'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: ScaffoldDbConnectionTool::class,
            method: 'scaffold',
            name: 'scaffold_db_connection',
            description: 'Create Config/databases.xml with a new connection if it doesn\'t exist '
                . 'yet, otherwise return a ready-to-paste snippet (never edits an existing file). '
                . 'dry_run defaults to true.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'name' => ['type' => 'string', 'description' => 'Connection name, e.g. "main".'],
                    'driver' => [
                        'type' => 'string',
                        'description' => 'Adapter driver (default "pdo").',
                        'enum' => ['pdo', 'eloquent', 'doctrine', 'doctrine_dbal', 'cycle'],
                    ],
                    'dry_run' => ['type' => 'boolean', 'description' => 'Preview only (default true).'],
                ],
                'required' => ['name'],
                'additionalProperties' => false,
            ],
        );

        $this->mcpTool(
            handlerFqcn: RunConsoleTool::class,
            method: 'run',
            name: 'run_console',
            description: 'Run one of the target app\'s own console commands, restricted to a '
                . 'non-destructive whitelist (' . implode(', ', ConsoleCommandWhitelist::commands()) . '); '
                . 'never migrations/deletes. Unlisted commands or options are refused.',
            inputSchema: [
                'type' => 'object',
                'properties' => [
                    'command' => [
                        'type' => 'string',
                        'description' => 'The command to run.',
                        'enum' => ConsoleCommandWhitelist::commands(),
                    ],
                    'args' => [
                        'type' => 'object',
                        'description' => 'Command-specific options, e.g. {"json": true} for routes:list.',
                    ],
                ],
                'required' => ['command'],
                'additionalProperties' => false,
            ],
        );
    }

    private function registerPrompts(): void
    {
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'newModule',
            name: 'new-module',
            description: 'Guidance + a checklist for adding a new module to a Quiote app.',
        );
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'addAction',
            name: 'add-action',
            description: 'Guidance for adding a new action (with verbs/validators/view) to a module.',
        );
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'addService',
            name: 'add-service',
            description: 'Guidance for adding a DI-resolved service/model to a Quiote app.',
        );
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'addPlugin',
            name: 'add-plugin',
            description: 'Guidance for writing a Quiote plugin that contributes via PluginRegistrar.',
        );
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'addDbConnection',
            name: 'add-db-connection',
            description: 'Guidance for declaring a new database connection.',
        );
        $this->mcpPrompt(
            ScaffoldPrompts::class,
            method: 'exposeMcpTool',
            name: 'expose-mcp-tool',
            description: 'Guidance for exposing an existing #[Route] action as an MCP tool.',
        );
    }

    /**
     * Reproduces the removed `PluginRegistrar::mcpTool()` -> `McpCatalog::addTool()` translation.
     *
     * @param array<string, mixed>|null $inputSchema
     * @param array<string, mixed>|null $outputSchema
     */
    private function mcpTool(
        string $handlerFqcn,
        ?string $method = null,
        ?string $name = null,
        ?string $description = null,
        ?array $inputSchema = null,
        ?array $outputSchema = null,
    ): void {
        McpCatalog::addTool(
            $method !== null ? [$handlerFqcn, $method] : $handlerFqcn,
            $name,
            null,
            $description,
            $inputSchema,
            $outputSchema,
        );
    }

    /** Reproduces the removed `PluginRegistrar::mcpResource()` -> `McpCatalog::addResource()` translation. */
    private function mcpResource(
        string $handlerFqcn,
        string $uri,
        ?string $method = null,
        ?string $name = null,
        ?string $description = null,
        ?string $mimeType = null,
    ): void {
        McpCatalog::addResource(
            $method !== null ? [$handlerFqcn, $method] : $handlerFqcn,
            $uri,
            $name,
            null,
            $description,
            $mimeType,
        );
    }

    /** Reproduces the removed `PluginRegistrar::mcpPrompt()` -> `McpCatalog::addPrompt()` translation. */
    private function mcpPrompt(
        string $handlerFqcn,
        ?string $method = null,
        ?string $name = null,
        ?string $description = null,
    ): void {
        McpCatalog::addPrompt(
            $method !== null ? [$handlerFqcn, $method] : $handlerFqcn,
            $name,
            null,
            $description,
        );
    }
}
