<?php

/**
 * GENERATED by `mcp:docs:sync` -- do not edit by hand.
 * Maps each MCP resource URI to its bundled file + frontmatter metadata.
 */

return array (
  'quiote-docs://advanced/advanced-validation' => 
  array (
    'file' => 'advanced/advanced-validation.md',
    'path' => 'advanced/advanced-validation',
    'title' => 'Advanced validation',
    'description' => 'Exports, logical operator groups, and custom validators with the fluent builder.',
  ),
  'quiote-docs://advanced/authentication-authorization' => 
  array (
    'file' => 'advanced/authentication-authorization.md',
    'path' => 'advanced/authentication-authorization',
    'title' => 'Authentication and authorization',
    'description' => 'The user/security model — securing actions, credentials, RBAC, CSRF, and rate limiting.',
  ),
  'quiote-docs://advanced/custom-middleware' => 
  array (
    'file' => 'advanced/custom-middleware.md',
    'path' => 'advanced/custom-middleware',
    'title' => 'Writing custom middleware',
    'description' => 'Add your own PSR-15 middleware to the pipeline and position it precisely.',
  ),
  'quiote-docs://advanced/custom-renderers' => 
  array (
    'file' => 'advanced/custom-renderers.md',
    'path' => 'advanced/custom-renderers',
    'title' => 'Writing a custom renderer',
    'description' => 'The renderer contract, initialize/render/reset, worker-mode reuse, wiring it into an output type, and shipping it as a package.',
  ),
  'quiote-docs://advanced/custom-validators' => 
  array (
    'file' => 'advanced/custom-validators.md',
    'path' => 'advanced/custom-validators',
    'title' => 'Writing a custom validator',
    'description' => 'The Validator base class contract, the validators.xml format, and wiring a custom validator in XML or PHP.',
  ),
  'quiote-docs://advanced/migrating-from-agavi' => 
  array (
    'file' => 'advanced/migrating-from-agavi.md',
    'path' => 'advanced/migrating-from-agavi',
    'title' => 'Migrating from Agavi',
    'description' => 'What carries over from Agavi, what changed, and a practical order to move an application across.',
  ),
  'quiote-docs://advanced/testing' => 
  array (
    'file' => 'advanced/testing.md',
    'path' => 'advanced/testing',
    'title' => 'Testing your application',
    'description' => 'Unit-testing actions and services, driving the full pipeline, and process isolation for worker-safe tests.',
  ),
  'quiote-docs://architecture/actions-and-views' => 
  array (
    'file' => 'architecture/actions-and-views.md',
    'path' => 'architecture/actions-and-views',
    'title' => 'Actions and views',
    'description' => 'The action/view contract — how methods are chosen, how data flows, and how view names resolve.',
  ),
  'quiote-docs://architecture/configuration' => 
  array (
    'file' => 'architecture/configuration.md',
    'path' => 'architecture/configuration',
    'title' => 'Configuration',
    'description' => 'Quiote\'s multi-format config system — PHP, YAML, or XML, mixed per file.',
  ),
  'quiote-docs://architecture/container' => 
  array (
    'file' => 'architecture/container.md',
    'path' => 'architecture/container',
    'title' => 'The DI container',
    'description' => 'Quiote\'s scope-aware dependency injection container, autowiring, and the service layer.',
  ),
  'quiote-docs://architecture/deployment' => 
  array (
    'file' => 'architecture/deployment.md',
    'path' => 'architecture/deployment',
    'title' => 'Worker mode & deployment',
    'description' => 'Running Quiote under FrankenPHP worker mode — the worker loop, per-request reset, state-leak hazards, environment variables, and Docker.',
  ),
  'quiote-docs://architecture/error-handling' => 
  array (
    'file' => 'architecture/error-handling.md',
    'path' => 'architecture/error-handling',
    'title' => 'Error handling',
    'description' => 'How exceptions flow through the pipeline, the developer vs safe renderers, and hooking or replacing error output.',
  ),
  'quiote-docs://architecture/events' => 
  array (
    'file' => 'architecture/events.md',
    'path' => 'architecture/events',
    'title' => 'Events',
    'description' => 'The PSR-14 event dispatcher, the framework lifecycle events, and writing listeners.',
  ),
  'quiote-docs://architecture/logging' => 
  array (
    'file' => 'architecture/logging.md',
    'path' => 'architecture/logging',
    'title' => 'Logging',
    'description' => 'Quiote\'s PSR-3 logging — category levels, sinks, structured events, and scopes.',
  ),
  'quiote-docs://architecture/middleware-pipeline' => 
  array (
    'file' => 'architecture/middleware-pipeline.md',
    'path' => 'architecture/middleware-pipeline',
    'title' => 'The middleware pipeline',
    'description' => 'What lives in Quiote\'s PSR-15 pipeline, in what order, and what each middleware does.',
  ),
  'quiote-docs://architecture/middleware-reference' => 
  array (
    'file' => 'architecture/middleware-reference.md',
    'path' => 'architecture/middleware-reference',
    'title' => 'Middleware reference',
    'description' => 'Every middleware in the default pipeline — what it does, how to configure it, and what each setting affects.',
  ),
  'quiote-docs://architecture/plugins' => 
  array (
    'file' => 'architecture/plugins.md',
    'path' => 'architecture/plugins',
    'title' => 'Plugins and extensibility',
    'description' => 'The plugin system — one lifecycle that lets a package contribute config, services, middleware, routes, events, commands, and HTTP clients.',
  ),
  'quiote-docs://architecture/request-lifecycle' => 
  array (
    'file' => 'architecture/request-lifecycle.md',
    'path' => 'architecture/request-lifecycle',
    'title' => 'The request lifecycle',
    'description' => 'How a request travels from the kernel through the middleware pipeline to a rendered response.',
  ),
  'quiote-docs://architecture/settings-reference' => 
  array (
    'file' => 'architecture/settings-reference.md',
    'path' => 'architecture/settings-reference',
    'title' => 'Settings reference',
    'description' => 'The configuration settings Quiote reads — core.* keys, factory parameters, environment variables, and where each is set.',
  ),
  'quiote-docs://architecture/telemetry' => 
  array (
    'file' => 'architecture/telemetry.md',
    'path' => 'architecture/telemetry',
    'title' => 'Telemetry',
    'description' => 'OpenTelemetry tracing and metrics — enabling it, the telemetry.* settings, sampling, spans, and log correlation.',
  ),
  'quiote-docs://basics/caching' => 
  array (
    'file' => 'basics/caching.md',
    'path' => 'basics/caching',
    'title' => 'Caching',
    'description' => 'The action/view output cache, the general-purpose cache, cache backends, and how to make an action cacheable.',
  ),
  'quiote-docs://basics/databases' => 
  array (
    'file' => 'basics/databases.md',
    'path' => 'basics/databases',
    'title' => 'Databases',
    'description' => 'The database layer — PDO plus first-class Eloquent, Doctrine, Cycle, and Propulsion adapters.',
  ),
  'quiote-docs://basics/http-client' => 
  array (
    'file' => 'basics/http-client.md',
    'path' => 'basics/http-client',
    'title' => 'HTTP client',
    'description' => 'Named PSR-18 HTTP clients — configuration, retries, transports, and automatic trace propagation.',
  ),
  'quiote-docs://basics/i18n' => 
  array (
    'file' => 'basics/i18n.md',
    'path' => 'basics/i18n',
    'title' => 'Translation and i18n',
    'description' => 'Translating messages and formatting numbers, currency, and dates with the TranslationManager.',
  ),
  'quiote-docs://basics/modules' => 
  array (
    'file' => 'basics/modules.md',
    'path' => 'basics/modules',
    'title' => 'Modules',
    'description' => 'How a Quiote application is organised into modules — layout, naming, discovery, and per-module config.',
  ),
  'quiote-docs://basics/output-types-and-content-negotiation' => 
  array (
    'file' => 'basics/output-types-and-content-negotiation.md',
    'path' => 'basics/output-types-and-content-negotiation',
    'title' => 'Output types and content negotiation',
    'description' => 'How Quiote picks an output format and how one view serves several.',
  ),
  'quiote-docs://basics/requests-and-responses' => 
  array (
    'file' => 'basics/requests-and-responses.md',
    'path' => 'basics/requests-and-responses',
    'title' => 'Requests and responses',
    'description' => 'The WebRequest and WebResponse API — parameters, cookies, headers, redirects, and forwarded-header handling.',
  ),
  'quiote-docs://basics/routing' => 
  array (
    'file' => 'basics/routing.md',
    'path' => 'basics/routing',
    'title' => 'Routing',
    'description' => 'Declaring routes with a Routing subclass and with #[Route] attributes.',
  ),
  'quiote-docs://basics/services-and-models' => 
  array (
    'file' => 'basics/services-and-models.md',
    'path' => 'basics/services-and-models',
    'title' => 'Services and models',
    'description' => 'Where business logic goes — writing a service with constructor injection, and using models as data objects.',
  ),
  'quiote-docs://basics/sessions' => 
  array (
    'file' => 'basics/sessions.md',
    'path' => 'basics/sessions',
    'title' => 'Sessions and storage',
    'description' => 'Session lifecycle, storage backends, cookie flags, and the worker-mode reset that keeps sessions from leaking.',
  ),
  'quiote-docs://basics/templates-and-rendering' => 
  array (
    'file' => 'basics/templates-and-rendering.md',
    'path' => 'basics/templates-and-rendering',
    'title' => 'Templates and rendering',
    'description' => 'How renderers, layouts, layers, and template variables produce a view\'s output.',
  ),
  'quiote-docs://basics/validation' => 
  array (
    'file' => 'basics/validation.md',
    'path' => 'basics/validation',
    'title' => 'Input validation',
    'description' => 'Declaring validators with the fluent PHP builder and reading validated input.',
  ),
  'quiote-docs://getting-started/cli' => 
  array (
    'file' => 'getting-started/cli.md',
    'path' => 'getting-started/cli',
    'title' => 'The command-line tool',
    'description' => 'The quiote CLI — scaffold an application, list routes, and inspect the environment.',
  ),
  'quiote-docs://getting-started/installation' => 
  array (
    'file' => 'getting-started/installation.md',
    'path' => 'getting-started/installation',
    'title' => 'Installation',
    'description' => 'Requirements and installation instructions for Quiote.',
  ),
  'quiote-docs://getting-started/introduction' => 
  array (
    'file' => 'getting-started/introduction.md',
    'path' => 'getting-started/introduction',
    'title' => 'Introduction',
    'description' => 'What Quiote is, where it came from, and whether it is the right framework for your project.',
  ),
  'quiote-docs://getting-started/mcp-assistant' => 
  array (
    'file' => 'getting-started/mcp-assistant.md',
    'path' => 'getting-started/mcp-assistant',
    'title' => 'The AI assistant (MCP server)',
    'description' => 'The Quiote Assistant MCP — an MCP server that gives AI coding agents authoritative knowledge of the framework, plus reflection, project introspection, and scaffolding tools.',
  ),
  'quiote-docs://getting-started/philosophy' => 
  array (
    'file' => 'getting-started/philosophy.md',
    'path' => 'getting-started/philosophy',
    'title' => 'Design philosophy',
    'description' => 'Why Quiote is deliberately unopinionated, and where opinionated defaults may live in the future.',
  ),
  'quiote-docs://getting-started/your-first-app' => 
  array (
    'file' => 'getting-started/your-first-app.md',
    'path' => 'getting-started/your-first-app',
    'title' => 'Your first application',
    'description' => 'Build and understand a minimal Quiote application, from the front controller to a rendered template.',
  ),
  'quiote-docs://plugins/official-packages' => 
  array (
    'file' => 'plugins/official-packages.md',
    'path' => 'plugins/official-packages',
    'title' => 'Official packages',
    'description' => 'The quioteframework/* packages extracted from the kernel — what each provides, what it depends on, and how to install and enable it.',
  ),
  'quiote-docs://plugins/overview' => 
  array (
    'file' => 'plugins/overview.md',
    'path' => 'plugins/overview',
    'title' => 'Plugins overview',
    'description' => 'How Quiote splits an unopinionated kernel from opinionated, separately-installable packages — and how you opt into the ones you want.',
  ),
);
