<?php

declare(strict_types=1);

namespace QuioteMcpAssistant\Tests\Unit\Mcp;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use QuioteMcpAssistant\Mcp\Conventions\ConventionCards;
use QuioteMcpAssistant\Mcp\Recipes\RecipeBook;
use QuioteMcpAssistant\Mcp\Resources\DocLibrary;

/**
 * The convention cards and recipes are the one hand-maintained knowledge
 * source; the docs they point at are regenerated by `mcp:docs:sync`. A page
 * renamed or dropped upstream therefore turns a cross-reference into a dead
 * `quiote-docs://` URI that an agent will happily try to `resources/read` --
 * and nothing else in the suite would notice. Every referenced URI is checked
 * against the committed manifest.
 */
final class DocReferenceIntegrityTest extends TestCase
{
    /** @return iterable<string, array{string, string}> */
    public static function referencedDocUris(): iterable
    {
        foreach (ConventionCards::topics() as $topic) {
            $card = ConventionCards::get($topic);
            self::assertNotNull($card);

            foreach (self::extractUris($card['body']) as $uri) {
                yield "convention card \"{$topic}\" -> {$uri}" => [$uri, "convention card \"{$topic}\""];
            }
        }

        foreach (RecipeBook::tasks() as $task) {
            $recipe = RecipeBook::get($task);
            self::assertNotNull($recipe);

            foreach ($recipe['steps'] as $i => $step) {
                $text = $step['description'] . "\n" . ($step['code'] ?? '');

                foreach (self::extractUris($text) as $uri) {
                    yield "recipe \"{$task}\" step {$i} -> {$uri}" => [$uri, "recipe \"{$task}\" step {$i}"];
                }
            }
        }
    }

    #[Test]
    #[DataProvider('referencedDocUris')]
    public function everyReferencedDocUriResolvesInTheManifest(string $uri, string $where): void
    {
        self::assertTrue(
            (new DocLibrary())->has($uri),
            "{$where} references \"{$uri}\", which is not in the docs manifest. "
            . 'The page was probably renamed or dropped upstream -- update the reference.',
        );
    }

    #[Test]
    public function theCardsAndRecipesActuallyCrossReferenceTheDocs(): void
    {
        // Guards the provider itself: a broken regex would silently yield
        // nothing and turn the test above into a no-op that always passes.
        self::assertGreaterThan(10, iterator_count(self::referencedDocUris()));
    }

    /** @return list<string> */
    private static function extractUris(string $text): array
    {
        preg_match_all('~quiote-docs://[a-z0-9\-]+/[a-z0-9\-]+~', $text, $matches);

        return array_values(array_unique($matches[0]));
    }
}
